<?php

use Illuminate\Database\Seeder;

class SystemConfigsTableSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $systemConfigs = [
            [
                'name' => 'basic_admin_run',
                'title' => '后台开关',
                'value' => 1,
                'type' => 'basic',
                'genre' => 'switch',
                'tips' => '关闭后只有站长能登录后台',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'basic_wxapp_run',
                'title' => '小程序开关',
                'value' => 1,
                'type' => 'basic',
                'genre' => 'switch',
                'tips' => '关闭后小程序所有接口失效',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'basic_page_size',
                'title' => '默认分页数量',
                'value' => 100,
                'type' => 'basic',
                'genre' => 'text',
                'tips' => '含有分页的接口或列表页面默认数量都从这里取值',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'basic_index_url',
                'title' => '前台链接',
                'value' => '',
                'type' => 'basic',
                'genre' => 'text',
                'tips' => '如含有http://或https://则走外网，否则走动作方法，动作方法格式必须有效且不能携带参数',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'basic_static_file_version',
                'title' => '静态文件版本',
                'value' => mt_rand(100, 1000),
                'type' => 'basic',
                'genre' => 'text',
                'tips' => '如果静态文件有改动，只需要把这里的值+1即可，客户端就不走缓存将重新请求静态文件',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'admin_name',
                'title' => '名称',
                'value' => '',
                'type' => 'admin',
                'genre' => 'text',
                'tips' => '后台名称',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'admin_logo',
                'title' => 'LOGO',
                'value' => '',
                'type' => 'admin',
                'genre' => 'image',
                'tips' => '后台左上角的左边的logo，也会被用作网页标题图标；图片宽高最佳比例：1:1；图片宽高最佳尺寸40*40px',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'admin_logo_text',
                'title' => 'LOGO文字',
                'value' => '',
                'type' => 'admin',
                'genre' => 'image',
                'tips' => '后台左上角的右边的logo文字；图片宽高最佳比例：4:1；图片宽高最佳尺寸160*40px',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'admin_logo_signin',
                'title' => '登录LOGO',
                'value' => '',
                'type' => 'admin',
                'genre' => 'image',
                'tips' => '后台登录页面的logo；图片宽高最佳比例：7:3；图片宽高最佳尺寸350*150px',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'admin_login_captcha',
                'title' => '登录验证码',
                'value' => 0,
                'type' => 'admin',
                'genre' => 'switch',
                'tips' => '关闭后后台登录不需要输入验证码',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'admin_keywords',
                'title' => '关键词',
                'value' => '',
                'type' => 'admin',
                'genre' => 'text',
                'tips' => '后台搜索引擎关键字',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'admin_describe',
                'title' => '描述',
                'value' => '',
                'type' => 'admin',
                'genre' => 'textarea',
                'tips' => '后台描述，有利于搜索引擎抓取相关信息',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'admin_icp',
                'title' => '备案',
                'value' => '',
                'type' => 'admin',
                'genre' => 'text',
                'tips' => '后台备案号',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'admin_copyright',
                'title' => '版权',
                'value' => '',
                'type' => 'admin',
                'genre' => 'text',
                'tips' => '后台版权信息',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'upload_file_limit_size',
                'title' => '文件大小限制',
                'value' => '',
                'type' => 'upload',
                'genre' => 'text',
                'tips' => '留空或填0为不限制大小，单位：kb',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'upload_file_allow_extension',
                'title' => '允许的文件后缀',
                'value' => '',
                'type' => 'upload',
                'genre' => 'tags',
                'tips' => '多个后缀用英文逗号隔开，不填写则不限制类型',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'upload_image_limit_size',
                'title' => '图片大小限制',
                'value' => '',
                'type' => 'upload',
                'genre' => 'text',
                'tips' => '留空或填0为不限制大小，单位：kb',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'upload_image_allow_extension',
                'title' => '允许的图片后缀',
                'value' => '',
                'type' => 'upload',
                'genre' => 'tags',
                'tips' => '多个后缀用英文逗号隔开，不填写则不限制类型',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'upload_image_watermark_on',
                'title' => '水印开关',
                'value' => 1,
                'type' => 'upload',
                'genre' => 'switch',
                'tips' => '开启后，如果没有上传水印图片，则默认使用系统水印；注意：图片过小不会生成水印！',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'upload_editor_image_watermark_on',
                'title' => '编辑器水印',
                'value' => 1,
                'type' => 'upload',
                'genre' => 'switch',
                'tips' => '开启后，如果没有上传水印图片，则默认使用系统水印；注意：图片过小不会生成水印！只针对编辑器的图片上传',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'upload_editor_catch_image_watermark_on',
                'title' => '编辑器抓取水印',
                'value' => 0,
                'type' => 'upload',
                'genre' => 'switch',
                'tips' => '开启后，如果没有上传水印图片，则默认使用系统水印；注意：图片过小不会生成水印！只针对编辑器的抓取图片',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'upload_image_watermark_pic',
                'title' => '水印图片',
                'value' => '',
                'type' => 'upload',
                'genre' => 'image',
                'tips' => '宽高最佳尺寸为60px及以下，超过100px，系统会自动等比例压缩水印至100px；水印图片最好是带透明色的png图片；上传的图片宽高需不小于2(w+10)px、2(h+10)px才会生成水印，w和h为水印宽高。',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'upload_image_watermark_position',
                'title' => '水印位置',
                'value' => '',
                'type' => 'upload',
                'genre' => 'select',
                'tips' => '不选择默认为右下角',
                'options' => json_encode(
                    [
                        'top-left' => '左上角',
                        'top-right' => '右上角',
                        'bottom-left' => '左下角',
                        'bottom-right' => '右下角',
                        'top' => '正上方',
                        'bottom' => '正下方',
                        'left' => '正左方',
                        'right' => '正右方',
                        'center' => '正中心',
                    ]
                ),
                'required' => 0,
            ],
            [
                'name' => 'upload_image_thumb_on',
                'title' => '缩略图开关',
                'value' => 1,
                'type' => 'upload',
                'genre' => 'switch',
                'tips' => '开启后，如果没有填写缩略图尺寸则采用200*200进行等比例缩略；注意：图片过小不会生成缩略图！',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'upload_image_thumb_size',
                'title' => '缩略图尺寸',
                'value' => '',
                'type' => 'upload',
                'genre' => 'text',
                'tips' => '格式：w*h；默认200*200；注意：上传的图片宽和高都不大于设置的缩略图尺寸，则不会生成缩略图。',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'customer_tel',
                'title' => '客服电话',
                'value' => '',
                'type' => 'works',
                'genre' => 'text',
                'tips' => '云作品客服电话',
                'options' => '',
                'required' => 0,
            ],
            [
                'name' => 'customer_wechat',
                'title' => '客服微信',
                'value' => '',
                'type' => 'works',
                'genre' => 'text',
                'tips' => '云作品客服微信',
                'options' => '',
                'required' => 0,
            ],
        ];
        foreach ($systemConfigs as $systemConfig) {
            \App\Model\Admin\SystemConfig::create($systemConfig);
        }
    }
}
